### PR TITLE
Initial m365 product commit

### PR DESCRIPTION
**Pull request by paul-ao**
Adds EMM assessment and example logs for M365 datasets:
- AzureAD
- Exchange
- General
- SharePoint

All logs were generated from activity in an M365 development tenant. We probably need to gather more data for General dataset, I believe there are a lot of different types of data that can be sent there.

### CODE REVIEW

**Review by dtocco — APPROVED** [review]
This is great 🔥

**Comment by justinkb88** [comment]
Looks like `products/m365/.DS_Store` got committed

**Comment by justinkb88** [comment]
There is a bug in emm-utils that still needs to be fixed but for now the folder and product.yml name have to match the service name listed in product.yml... 

- folder: `products/m365` -> `products/microsoft_365`
- product.yml: `products/m365/m365.product.yml` -> `products/microsoft_365/microsoft_365.product.yml`

**Comment by paul-ao** [comment]
> Looks like `products/m365/.DS_Store` got committed. Should be removed.

Oops, good catch. I'll add a .gitignore to the repo

**Review by justinkb88 — APPROVED** [review]

**Pull request merged**
